### ISSUE TITLE
Core Data Corruption with migration from old sqlite file

### ISSUE THREAD

**Issue by bevbomb** [carambalabs/SugarRecord#319]
## What
I'm rebuilding an app with the latest SugarRecord and keeping the old sqlite store from the old versions of the app, but some users experience corruption which causes a fatal error when initialising.

## Context
I'm migrating an existing sqlite store from older versions of an app using the old SugarRecord, some users can migrate fine from the old version on the store to the new beta Testflight, but a few have come back as corrupted causing a fatal every time producing the same error.

`fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=259 "The file couldn’t be opened because it isn’t in the correct format." UserInfo={NSSQLiteErrorDomain=11, NSUnderlyingException=Fatal error. The database at /var/mobile/Containers/Data/Application/XXX/Library/Application Support/store/databasename.sqlite is corrupted. SQLite error code:11, 'database disk image is malformed'}:`

## Proposal
I basically need to know if anyone else has experienced this before? and is there any way to resolve the issue without dataloss?

**Comment by pepibumur** [comment]
Hi @bevbomb, did you update your data model when you bumped the SugarRecord version? SugarRecord shouldn't have any impact on these images since it's just a wrapper that makes the setup and the operations easier. I have found [this trick](https://gist.github.com/Pegolon/871206) which might be useful for your case. Let me know if it works.
