### ISSUE TITLE
Realm update objects

### ISSUE THREAD

**Issue by piv199** [carambalabs/SugarRecord#320]
#235 
#218 was merged, but currently, I can't see `update: true` in Realm extension...

I'm trying to update objects in Realm if they exist or insert new ones, but get an error `Can't create object with existing primary key value`.

The solution is to apply #218 pr again. Also there were talks about checking on `primaryKey`.

**Comment by pepibumur** [comment]
Hello @piv199 , we've just released a new version of SugarRecord removing Realm support https://github.com/carambalabs/SugarRecord/releases/tag/3.1.1. 

We believe that the API of Realm is very mature and simple enough to need another wrapper on top of it. However, this layer keeps making sense with Core Data, where the setup and the operations introduce some overhead.

I'll close this issue since it's out of the scope of the library.
